apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-gateway-pods
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: student
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: exam-management