services:
  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: ./services/gateway
    ports:
      - "8080:8080"
    networks:
      - shared
      - frontend

  student:
    image: student
    container_name: student
    build:
      context: ./services/student
    networks:
      - shared
      - student_internal
    depends_on:
      - student-db
    environment:
      DATABASE_URI: ${DATABASE_URI:?Please set DATABASE_URI in your local environment}

  student-db:
    image: postgres
    container_name: student-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in your local environment}
    networks:
      - student_internal

  exam:
    image: exam
    container_name: exam
    build:
      context: ./services/exam
    networks:
      - shared
      - exam_internal
    depends_on:
      - exam-db
    environment:
      DATABASE_URI: ${DATABASE_URI:?Please set DATABASE_URI in your local environment}

  exam-db:
    image: postgres
    container_name: exam-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in your local environment}
    networks:
      - exam_internal

  exam-management:
    image: exam-management
    container_name: exam-management
    build:
      context: ./services/exam-management
    networks:
      - shared
      - exam_management_internal
    depends_on:
      - exam-management-db
    environment:
      DATABASE_URI: ${DATABASE_URI:?Please set DATABASE_URI in your local environment}

  exam-management-db:
    image: postgres
    container_name: exam-management-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in your local environment}
    networks:
      - exam_management_internal

  translation:
    image: translation
    container_name: translation
    build:
      context: ./services/translation
    networks:
      - shared
      - translation_internal
    depends_on:
      - translation-db
    environment:
      DATABASE_URI: ${DATABASE_URI:?Please set DATABASE_URI in your local environment}

  translation-db:
    image: postgres
    container_name: translation-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Please set POSTGRES_PASSWORD in your local environment}
    networks:
      - translation_internal

networks:
  frontend:
  shared:
  student_internal:
  exam_internal:
  exam_management_internal:
  translation_internal:
