apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "acd-microservice-go.examname" . }}
  labels:
    {{- include "acd-microservice-go.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "acd-microservice-go.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "acd-microservice-go.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.exam.name }}
          image: "{{ .Values.exam.image.repository }}:{{ .Values.exam.image.tag }}"
          ports:
            - containerPort: {{ .Values.exam.service.port }}
