apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.exam.name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.exam.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.exam.port }}
      targetPort: {{ .Values.exam.port }}
