apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.exam.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.exam.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.exam.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.exam.name }}
    spec:
      containers:
        - name: {{ .Values.exam.name }}
          image: "{{ .Values.exam.name }}:{{ .Values.exam.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.exam.port }}
