apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.student.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.student.name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.student.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.student.name }}
    spec:
      containers:
        - name: {{ .Values.student.name }}
          image: "{{ .Values.student.name }}:{{ .Values.student.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.student.port }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: student-db-app
                  key: uri
