apiVersion: v1
kind: Service
metadata:
  name: {{ include "acd-microservice-go.studentname" . }}
  labels:
    {{- include "acd-microservice-go.labels" . | nindent 4 }}
spec:
  type: {{ .Values.student.service.type }}
  ports:
    - port: {{ .Values.student.service.port }}
      targetPort: {{ .Values.student.service.targetPort }}
  selector:
    {{- include "acd-microservice-go.selectorLabels" . | nindent 4 }}
