apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-student-pods
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: student
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: exam-management
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: gateway
  egress: []