@startuml
left to right direction
actor Student as s

package Prüfungsverwaltung {
  usecase "Prüfung abmelden" as UC1
  usecase "Prüfung anmelden" as UC2
  usecase "Angemeldete Prüfungen einsehen" as UC3
}

s --> UC1
s --> UC2
s --> UC3
@enduml
