apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: exam-management-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: exam-management
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: gateway
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: exam
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: student
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: translation