frontend:
  name: "frontend"
  tag: latest
  port: 80

exam:
  name: "exam"
  tag: latest
  port: 8080

examManagement:
  name: "exam-management"
  tag: latest
  port: 8080

gateway:
  name: "gateway"
  tag: latest
  port: 8080

student:
  name: "student"
  tag: latest
  port: 8080

translation:
  name: "translation"
  tag: latest
  port: 8080
